# ######################################################################################################################
# For more information on Docker storage drivers see:
# https://docs.docker.com/engine/userguide/storagedriver/selectadriver/#supported-storage-drivers-per-linux-distribution
# ######################################################################################################################

---
  - name: create /etc/docker directory
    file:
      path: /etc/docker
      state: directory

  # The overlay2 docker storage driver will be used for the following operating systems:
  # - RHEL 7.4
  # - Ubuntu 16 and higher.
  - name: write overlay2 docker config file
    template:
      src: overlay2-daemon.json
      dest: /etc/docker/daemon.json
    when: (ansible_os_family == "RedHat" and ansible_distribution_version == '7.4') or
          (ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= '16')

  # The devicemapper docker storage driver will be used for the following operating systems:
  # - All RHEL versions other than 7.4,
  # - All CentOS versions
  # - All Ubuntu versions lower than 16.
  - name: write devicemapper docker config file
    template:
      src: devicemapper-daemon.json
      dest: /etc/docker/daemon.json
    when: (ansible_os_family == "RedHat" and ansible_distribution_version != '7.4') or
          (ansible_distribution == "Ubuntu" and ansible_distribution_major_version < '16')

  # start and verify that Docker installed successfully and is running
  - name: start docker service
    service:
      name: docker
      state: started
      enabled: yes
    when: force_docker_restart is not defined or force_docker_restart|bool == false # only run if not going to restart right after

  # force_kubelet_restart=true to force restart
  # on install, service will be started with the task before this
  # on upgrade, this will be restarted only of the package was upgraded
  - name: restart docker service
    service:
      name: docker
      state: restarted
      enabled: yes
    when: >
      (force_docker_restart is defined and force_docker_restart|bool == true) or
      ((upgrading is defined and upgrading|bool == true) and
      (allow_package_installation|bool == false or
      ((docker_installation_rpm is defined and docker_installation_rpm.changed == true) or
      (docker_installation_deb is defined and docker_installation_deb.changed == true))))

  - name: verify docker is running
    command: docker ps

  - name: run docker login
    command: docker login -u {{ docker_registry_username }} -p {{ docker_registry_password }} {{ docker_registry_full_url }}
    when: docker_registry_username != ""